# Generated by Django 2.2.2 on 2019-06-14 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 14, 11, 24, 50, 748057))),
                ('end_date_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 14, 11, 24, 50, 748057))),
                ('notes', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'fields',
            },
        ),
    ]
