# Generated by Django 2.2.2 on 2019-06-14 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSVapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='end_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 14, 11, 52, 5, 385338)),
        ),
        migrations.AlterField(
            model_name='form',
            name='start_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 14, 11, 52, 5, 385338)),
        ),
        migrations.AlterModelTable(
            name='form',
            table=None,
        ),
    ]
