# Generated by Django 2.2.2 on 2019-06-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSVapp', '0002_auto_20190614_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='form',
            name='notes',
        ),
        migrations.AlterField(
            model_name='form',
            name='start_date_time',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
