# Generated by Django 2.2.2 on 2019-06-14 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSVapp', '0003_auto_20190614_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='form1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=200)),
                ('start_date_time1', models.DateTimeField(verbose_name='date published')),
                ('q1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSVapp.form')),
            ],
        ),
    ]
